baseURL       = "https://abdulsametileri.github.io/hk-website/"
languageCode  = "tr"
title         = "Ulus Etiket Matbaacılık ve Ambalaj - Antalya - Isparta - Burdur - Alanya"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Anasayfa"
    url     = ""
    weight  = 1
#  [[menu.nav]]
#    name    = "Kurumsal"
#    url     = "kurumsal"
#    weight  = 2
  [[menu.nav]]
    name    = "Ürünler"
    url     = "urunler"
    weight  = 3
  #[[menu.nav]]
   # name    = "Blog"
    #url     = "blog"
    #weight  = 4
  [[menu.nav]]
    name    = "İletişim"
    url     = "iletisim"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  fabform  = "https://fabform.io/f/T-3OasE"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Ad"
    placeholder_last_name         = "Soyad"
    placeholder_email             = "E-mail"
    placeholder_telefon           = "Telefon"
    placeholder_about_the_project = "Mesajınız"
    send_message                  = "Gönder"

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/cta-background.jpg"
    heading               = "Ulus Etiket Matbaacılık ve Ambalaj"
    tagline               = ""
    primary_button        = "Ürünlerimiz"
    primary_button_url    = "urunler"
    secondary_button      = "İletişim"
    secondary_button_url  = "iletisim"

  [params.portfolio]
    enable    = true
    title     = "Ürünler"
    subtitle  = ""

  [params.call_to_action]
    enable              = false
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "İletişim"
      address = "Kışla Mah. 47. Sokak 7/A Muratpaşa / ANTALYA"
      phone   = "0 544 242 79 35"
      email   = "etiket@3ketiket.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sayfalar"
        [[params.footer.sitemap.link]]
          name = "Ürünler"
          url  = "urunler"
        [[params.footer.sitemap.link]]
          name = "İletişim"
          url  = "iletisim"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Ulus Etiket Matbaacılık ve Ambalaj"
        description = "Buraya açıklama ekleyelim"